name: .NET Core App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    env:
      Solution_Name: EatEase.sln                         
    steps:
    - name: Checkout
      uses: actions/checkout@v20
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v20
      with:
        dotnet-version: 8.0.x
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Clean
      run: dotnet clean
    - name: Build
      run: dotnet build --configuration Release --no-restore
